-- Chronos — volledige, correcte landenlijst (ISO 3166-1, NL + EN), beheerder-
-- bewerkbaar via Instellingen. Vervangt de hardcoded LANDNAMEN-lijst in
-- src/lib/dossiernummer.ts als bron voor landnamen in de app; die const blijft
-- alleen nog als seed-data hieronder.

create table public.landcodes (
  iso_code text primary key,
  naam_nl text not null,
  naam_en text not null
);

comment on table public.landcodes is 'Landnamen per ISO 3166-1-code (plus praktijk-codes zoals WO/EU/BX/UK), beheerder-bewerkbaar.';

alter table public.landcodes enable row level security;

create policy "landcodes_select_all" on public.landcodes
  for select to authenticated using (true);

create policy "landcodes_write_beheerder" on public.landcodes
  for all to authenticated
  using (public.is_role('beheerder'))
  with check (public.is_role('beheerder'));

grant all on public.landcodes to authenticated, service_role;

insert into public.landcodes (iso_code, naam_nl, naam_en) values
  ('AD','Andorra','Andorra'),
  ('AE','Verenigde Arabische Emiraten','United Arab Emirates'),
  ('AF','Afghanistan','Afghanistan'),
  ('AG','Antigua en Barbuda','Antigua and Barbuda'),
  ('AI','Anguilla','Anguilla'),
  ('AL','Albanië','Albania'),
  ('AM','Armenië','Armenia'),
  ('AO','Angola','Angola'),
  ('AQ','Antarctica','Antarctica'),
  ('AR','Argentinië','Argentina'),
  ('AS','Amerikaans-Samoa','American Samoa'),
  ('AT','Oostenrijk','Austria'),
  ('AU','Australië','Australia'),
  ('AW','Aruba','Aruba'),
  ('AX','Ålandeilanden','Åland Islands'),
  ('AZ','Azerbeidzjan','Azerbaijan'),
  ('BA','Bosnië en Herzegovina','Bosnia and Herzegovina'),
  ('BB','Barbados','Barbados'),
  ('BD','Bangladesh','Bangladesh'),
  ('BE','België','Belgium'),
  ('BF','Burkina Faso','Burkina Faso'),
  ('BG','Bulgarije','Bulgaria'),
  ('BH','Bahrein','Bahrain'),
  ('BI','Burundi','Burundi'),
  ('BJ','Benin','Benin'),
  ('BL','Saint-Barthélemy','Saint Barthélemy'),
  ('BM','Bermuda','Bermuda'),
  ('BN','Brunei','Brunei Darussalam'),
  ('BO','Bolivia','Bolivia'),
  ('BQ','Bonaire, Sint Eustatius en Saba','Bonaire, Sint Eustatius and Saba'),
  ('BR','Brazilië','Brazil'),
  ('BS','Bahama''s','Bahamas'),
  ('BT','Bhutan','Bhutan'),
  ('BV','Bouveteiland','Bouvet Island'),
  ('BW','Botswana','Botswana'),
  ('BY','Wit-Rusland','Belarus'),
  ('BZ','Belize','Belize'),
  ('CA','Canada','Canada'),
  ('CC','Cocoseilanden','Cocos (Keeling) Islands'),
  ('CD','Congo-Kinshasa (DR Congo)','Congo (Democratic Republic of the)'),
  ('CF','Centraal-Afrikaanse Republiek','Central African Republic'),
  ('CG','Congo-Brazzaville','Congo'),
  ('CH','Zwitserland','Switzerland'),
  ('CI','Ivoorkust','Côte d''Ivoire'),
  ('CK','Cookeilanden','Cook Islands'),
  ('CL','Chili','Chile'),
  ('CM','Kameroen','Cameroon'),
  ('CN','China','China'),
  ('CO','Colombia','Colombia'),
  ('CR','Costa Rica','Costa Rica'),
  ('CU','Cuba','Cuba'),
  ('CV','Kaapverdië','Cabo Verde'),
  ('CW','Curaçao','Curaçao'),
  ('CX','Christmaseiland','Christmas Island'),
  ('CY','Cyprus','Cyprus'),
  ('CZ','Tsjechië','Czechia'),
  ('DE','Duitsland','Germany'),
  ('DJ','Djibouti','Djibouti'),
  ('DK','Denemarken','Denmark'),
  ('DM','Dominica','Dominica'),
  ('DO','Dominicaanse Republiek','Dominican Republic'),
  ('DZ','Algerije','Algeria'),
  ('EC','Ecuador','Ecuador'),
  ('EE','Estland','Estonia'),
  ('EG','Egypte','Egypt'),
  ('EH','Westelijke Sahara','Western Sahara'),
  ('ER','Eritrea','Eritrea'),
  ('ES','Spanje','Spain'),
  ('ET','Ethiopië','Ethiopia'),
  ('FI','Finland','Finland'),
  ('FJ','Fiji','Fiji'),
  ('FK','Falklandeilanden','Falkland Islands'),
  ('FM','Micronesië','Micronesia'),
  ('FO','Faeröer','Faroe Islands'),
  ('FR','Frankrijk','France'),
  ('GA','Gabon','Gabon'),
  ('GB','Verenigd Koninkrijk','United Kingdom'),
  ('GD','Grenada','Grenada'),
  ('GE','Georgië','Georgia'),
  ('GF','Frans-Guyana','French Guiana'),
  ('GG','Guernsey','Guernsey'),
  ('GH','Ghana','Ghana'),
  ('GI','Gibraltar','Gibraltar'),
  ('GL','Groenland','Greenland'),
  ('GM','Gambia','Gambia'),
  ('GN','Guinee','Guinea'),
  ('GP','Guadeloupe','Guadeloupe'),
  ('GQ','Equatoriaal-Guinea','Equatorial Guinea'),
  ('GR','Griekenland','Greece'),
  ('GS','Zuid-Georgia en de Zuidelijke Sandwicheilanden','South Georgia and the South Sandwich Islands'),
  ('GT','Guatemala','Guatemala'),
  ('GU','Guam','Guam'),
  ('GW','Guinee-Bissau','Guinea-Bissau'),
  ('GY','Guyana','Guyana'),
  ('HK','Hongkong','Hong Kong'),
  ('HM','Heard- en McDonaldeilanden','Heard Island and McDonald Islands'),
  ('HN','Honduras','Honduras'),
  ('HR','Kroatië','Croatia'),
  ('HT','Haïti','Haiti'),
  ('HU','Hongarije','Hungary'),
  ('ID','Indonesië','Indonesia'),
  ('IE','Ierland','Ireland'),
  ('IL','Israël','Israel'),
  ('IM','Isle of Man','Isle of Man'),
  ('IN','India','India'),
  ('IO','Brits Indische Oceaanterritorium','British Indian Ocean Territory'),
  ('IQ','Irak','Iraq'),
  ('IR','Iran','Iran'),
  ('IS','IJsland','Iceland'),
  ('IT','Italië','Italy'),
  ('JE','Jersey','Jersey'),
  ('JM','Jamaica','Jamaica'),
  ('JO','Jordanië','Jordan'),
  ('JP','Japan','Japan'),
  ('KE','Kenia','Kenya'),
  ('KG','Kirgizië','Kyrgyzstan'),
  ('KH','Cambodja','Cambodia'),
  ('KI','Kiribati','Kiribati'),
  ('KM','Comoren','Comoros'),
  ('KN','Saint Kitts en Nevis','Saint Kitts and Nevis'),
  ('KP','Noord-Korea','North Korea'),
  ('KR','Zuid-Korea','South Korea'),
  ('KW','Koeweit','Kuwait'),
  ('KY','Caymaneilanden','Cayman Islands'),
  ('KZ','Kazachstan','Kazakhstan'),
  ('LA','Laos','Laos'),
  ('LB','Libanon','Lebanon'),
  ('LC','Saint Lucia','Saint Lucia'),
  ('LI','Liechtenstein','Liechtenstein'),
  ('LK','Sri Lanka','Sri Lanka'),
  ('LR','Liberia','Liberia'),
  ('LS','Lesotho','Lesotho'),
  ('LT','Litouwen','Lithuania'),
  ('LU','Luxemburg','Luxembourg'),
  ('LV','Letland','Latvia'),
  ('LY','Libië','Libya'),
  ('MA','Marokko','Morocco'),
  ('MC','Monaco','Monaco'),
  ('MD','Moldavië','Moldova'),
  ('ME','Montenegro','Montenegro'),
  ('MF','Saint-Martin','Saint Martin (French part)'),
  ('MG','Madagaskar','Madagascar'),
  ('MH','Marshalleilanden','Marshall Islands'),
  ('MK','Noord-Macedonië','North Macedonia'),
  ('ML','Mali','Mali'),
  ('MM','Myanmar','Myanmar'),
  ('MN','Mongolië','Mongolia'),
  ('MO','Macau','Macao'),
  ('MP','Noordelijke Marianen','Northern Mariana Islands'),
  ('MQ','Martinique','Martinique'),
  ('MR','Mauritanië','Mauritania'),
  ('MS','Montserrat','Montserrat'),
  ('MT','Malta','Malta'),
  ('MU','Mauritius','Mauritius'),
  ('MV','Maldiven','Maldives'),
  ('MW','Malawi','Malawi'),
  ('MX','Mexico','Mexico'),
  ('MY','Maleisië','Malaysia'),
  ('MZ','Mozambique','Mozambique'),
  ('NA','Namibië','Namibia'),
  ('NC','Nieuw-Caledonië','New Caledonia'),
  ('NE','Niger','Niger'),
  ('NF','Norfolkeiland','Norfolk Island'),
  ('NG','Nigeria','Nigeria'),
  ('NI','Nicaragua','Nicaragua'),
  ('NL','Nederland','Netherlands'),
  ('NO','Noorwegen','Norway'),
  ('NP','Nepal','Nepal'),
  ('NR','Nauru','Nauru'),
  ('NU','Niue','Niue'),
  ('NZ','Nieuw-Zeeland','New Zealand'),
  ('OM','Oman','Oman'),
  ('PA','Panama','Panama'),
  ('PE','Peru','Peru'),
  ('PF','Frans-Polynesië','French Polynesia'),
  ('PG','Papoea-Nieuw-Guinea','Papua New Guinea'),
  ('PH','Filipijnen','Philippines'),
  ('PK','Pakistan','Pakistan'),
  ('PL','Polen','Poland'),
  ('PM','Saint-Pierre en Miquelon','Saint Pierre and Miquelon'),
  ('PN','Pitcairneilanden','Pitcairn'),
  ('PR','Puerto Rico','Puerto Rico'),
  ('PS','Palestina','Palestine, State of'),
  ('PT','Portugal','Portugal'),
  ('PW','Palau','Palau'),
  ('PY','Paraguay','Paraguay'),
  ('QA','Qatar','Qatar'),
  ('RE','Réunion','Réunion'),
  ('RO','Roemenië','Romania'),
  ('RS','Serbië','Serbia'),
  ('RU','Rusland','Russia'),
  ('RW','Rwanda','Rwanda'),
  ('SA','Saoedi-Arabië','Saudi Arabia'),
  ('SB','Salomonseilanden','Solomon Islands'),
  ('SC','Seychellen','Seychelles'),
  ('SD','Soedan','Sudan'),
  ('SE','Zweden','Sweden'),
  ('SG','Singapore','Singapore'),
  ('SH','Sint-Helena','Saint Helena'),
  ('SI','Slovenië','Slovenia'),
  ('SJ','Svalbard en Jan Mayen','Svalbard and Jan Mayen'),
  ('SK','Slowakije','Slovakia'),
  ('SL','Sierra Leone','Sierra Leone'),
  ('SM','San Marino','San Marino'),
  ('SN','Senegal','Senegal'),
  ('SO','Somalië','Somalia'),
  ('SR','Suriname','Suriname'),
  ('SS','Zuid-Soedan','South Sudan'),
  ('ST','Sao Tomé en Principe','Sao Tome and Principe'),
  ('SV','El Salvador','El Salvador'),
  ('SX','Sint Maarten','Sint Maarten'),
  ('SY','Syrië','Syria'),
  ('SZ','Eswatini','Eswatini'),
  ('TC','Turks- en Caicoseilanden','Turks and Caicos Islands'),
  ('TD','Tsjaad','Chad'),
  ('TF','Franse Zuidelijke en Antarctische Gebieden','French Southern Territories'),
  ('TG','Togo','Togo'),
  ('TH','Thailand','Thailand'),
  ('TJ','Tadzjikistan','Tajikistan'),
  ('TK','Tokelau','Tokelau'),
  ('TL','Oost-Timor','Timor-Leste'),
  ('TM','Turkmenistan','Turkmenistan'),
  ('TN','Tunesië','Tunisia'),
  ('TO','Tonga','Tonga'),
  ('TR','Turkije','Turkey'),
  ('TT','Trinidad en Tobago','Trinidad and Tobago'),
  ('TV','Tuvalu','Tuvalu'),
  ('TW','Taiwan','Taiwan'),
  ('TZ','Tanzania','Tanzania'),
  ('UA','Oekraïne','Ukraine'),
  ('UG','Oeganda','Uganda'),
  ('US','Verenigde Staten','United States'),
  ('UY','Uruguay','Uruguay'),
  ('UZ','Oezbekistan','Uzbekistan'),
  ('VA','Vaticaanstad','Holy See'),
  ('VC','Saint Vincent en de Grenadines','Saint Vincent and the Grenadines'),
  ('VE','Venezuela','Venezuela'),
  ('VG','Britse Maagdeneilanden','Virgin Islands (British)'),
  ('VI','Amerikaanse Maagdeneilanden','Virgin Islands (U.S.)'),
  ('VN','Vietnam','Vietnam'),
  ('VU','Vanuatu','Vanuatu'),
  ('WF','Wallis en Futuna','Wallis and Futuna'),
  ('WS','Samoa','Samoa'),
  ('YE','Jemen','Yemen'),
  ('YT','Mayotte','Mayotte'),
  ('ZA','Zuid-Afrika','South Africa'),
  ('ZM','Zambia','Zambia'),
  ('ZW','Zimbabwe','Zimbabwe'),
  ('WO','Internationale registratie','International registration'),
  ('EU','Europese Unie','European Union'),
  ('BX','Benelux','Benelux'),
  ('UK','Verenigd Koninkrijk','United Kingdom');
